name: localizacao_flutter
description: "Teste de localizacao e aceleracao"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  geolocator: ^11.0.0
  permission_handler: ^12.0.0
  provider: ^6.1.5

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icone2.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
